name: deep_sim3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - fbprophet=0.7.1
  - pip:
    - pandas
    - nltk==3.7
    - networkx==2.5
    - numpy
    - sympy==1.7.1
    - scikit-learn==1.1.2
    - hyperopt==0.2.5
    - jellyfish
    - tensorflow==2.4.0
    - keras==2.4.3
    - opyenxes==0.3.0
    - graphviz==0.15
    - git+http://github.com/Mcamargo85/support_modules.git
    - gensim
    - seaborn
    - fitter
