name: deep_sim3
channels:
  - defaults
dependencies:
  - python==3.8.5
  - spyder==5.0.0
  - pandas
  - lxml
  - matplotlib
  - nltk
  - scikit-learn
  - ipywidgets
  - pip:
    - hyperopt
    - jellyfish
    - keras
    - pm4py
    - tensorflow
    - opyenxes
    - git+http://github.com/Mcamargo85/support_modules.git
